# Generated by Django 5.0.3 on 2024-03-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyHall', '0003_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='resource',
            field=models.ManyToManyField(related_name='resources', to='StudyHall.resources'),
        ),
    ]
