# Generated by Django 5.0.3 on 2024-03-28 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyHall', '0004_room_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='resource',
        ),
        migrations.AlterField(
            model_name='roomchats',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudyHall.room'),
        ),
        migrations.DeleteModel(
            name='Resources',
        ),
    ]
